[package]
name = "merkle-tree-nostd"
version = "0.1.0"
authors = ["dhy1996 <dhy1996@live.com.sg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
ring = "0.16.20"